version: "3.9"
services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_DB: "bet"
      POSTGRES_USER: "bet_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "15432:5432"
