version: "3.9"
services:
  app:
    build:
      context: .
    container_name: bet-app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3
    container_name: bet-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"


  liquibase:
    image: 'liquibase/liquibase'
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./liquibase.properties:/liquibase/liquibase.properties
    command: --changeLogFile=/liquibase/changelog/db.changelog.xml --url=jdbc:postgresql://postgres:5432/postgres --username=postgres --password=password update
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LIQUIBASE_CHANGELOG: /liquibase/changelog/db.changelog.xml

volumes:
  postgres-data:
