datasource:
  db-bet:
    hikari:
      driver-class-name: org.postgresql.Driver
#      jdbc-url: "jdbc:postgresql://postgres:5432/postgres"
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      username: "postgres"
      password: "postgres"
#      jdbc-url: "jdbc:postgresql://${POSTGRES_SERVER:postgres}:${POSTGRES_EXTERNAL_PORT:15432}/${POSTGRES_DB:bet}"
#      username: "${POSTGRES_USER:bet_user}"
#      password: "${POSTGRES_PASSWORD:password}"
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8090
spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: true
    change-log: db.changelog.xml
    drop-first: false
logging:
  level:
    org.springframework: WARN
app:
  telegram:
    bot:
      bet:
        token: "${BOT_TOKEN:7213455816:AAEluuiws56Ya9GdkmtyZEtmC6WT07RJs9I}"
        name: "${BOT_NAME:testuefaeurobot}"
  uefa:
    integration:
      url: "https://match.uefa.com/v5/"
